package com.fpt.aptech.matrimony.model;
// Generated Sep 6, 2017 4:21:07 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FriendsRequest generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "FRIENDS_REQUEST", catalog = "matrimony")
public class FriendsRequest implements java.io.Serializable {

	private Long id;
	private String userRequest;
	private String userReceive;
	private Integer status;
	private Date createDatetime;
	private Date updateDatetime;

	public FriendsRequest() {
	}

	public FriendsRequest(String userRequest, String userReceive, Integer status, Date createDatetime,
			Date updateDatetime) {
		this.userRequest = userRequest;
		this.userReceive = userReceive;
		this.status = status;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "user_request", nullable=false, length = 30)
	public String getUserRequest() {
		return this.userRequest;
	}

	public void setUserRequest(String userRequest) {
		this.userRequest = userRequest;
	}

	@Column(name = "user_receive", nullable=false, length = 30)
	public String getUserReceive() {
		return this.userReceive;
	}

	public void setUserReceive(String userReceive) {
		this.userReceive = userReceive;
	}

	@Column(name = "status", nullable=false)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
