package com.fpt.aptech.matrimony.model;
// Generated Sep 6, 2017 4:21:07 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserDocument generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "USER_DOCUMENT", catalog = "matrimony")
public class UserDocument implements java.io.Serializable {

	private Long id;
	private long userId;
	private String name;
	private String description;
	private String type;
	private byte[] content;

	public UserDocument() {
	}

	public UserDocument(long userId, String name, String type, byte[] content) {
		this.userId = userId;
		this.name = name;
		this.type = type;
		this.content = content;
	}

	public UserDocument(long userId, String name, String description, String type, byte[] content) {
		this.userId = userId;
		this.name = name;
		this.description = description;
		this.type = type;
		this.content = content;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type", nullable = false, length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "content", nullable = false)
	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

}
